# Generated by Django 3.0.6 on 2020-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='sound_file',
            field=models.FileField(blank=True, upload_to='sounds/'),
        ),
    ]
