# Generated by Django 3.0.6 on 2020-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='auto_stop',
            field=models.BooleanField(default=True),
        ),
    ]
