# Generated by Django 3.0.6 on 2020-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_script_auto_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_name',
            field=models.CharField(default='default.py', max_length=128),
            preserve_default=False,
        ),
    ]
