# Generated by Django 3.0.6 on 2020-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_script_script_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
