# Generated by Django 3.0.6 on 2020-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200531_1500'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='twitchemote',
            name='api_twitche_twitchI_5a5442_idx',
        ),
        migrations.RenameField(
            model_name='twitchemote',
            old_name='twitchId',
            new_name='twitch_id',
        ),
        migrations.AddIndex(
            model_name='twitchemote',
            index=models.Index(fields=['twitch_id'], name='api_twitche_twitch__41744a_idx'),
        ),
    ]
