# Generated by Django 3.0.6 on 2020-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200531_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchemote',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='twitchemote',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
