# Generated by Django 3.0.6 on 2020-05-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200531_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitchEmote',
        ),
    ]
