# Generated by Django 3.0.6 on 2020-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_twitchemote'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='keyvalue',
            index=models.Index(fields=['key'], name='api_keyvalu_key_fc8e70_idx'),
        ),
    ]
