# Generated by Django 3.0.6 on 2020-06-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200602_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvalue',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
