# Generated by Django 3.0.6 on 2020-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_twitchclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchEmote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
