# Generated by Django 3.0.6 on 2020-06-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_twitchemote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitchEmote',
            new_name='CustomEmote',
        ),
    ]
