# Generated by Django 3.0.6 on 2020-06-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200604_1546'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customemote',
            index=models.Index(fields=['name'], name='api_custome_name_4da326_idx'),
        ),
    ]
