# Generated by Django 3.0.6 on 2020-06-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200604_1555'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customemote',
            name='api_custome_name_4da326_idx',
        ),
        migrations.RemoveField(
            model_name='customemote',
            name='id',
        ),
        migrations.AlterField(
            model_name='customemote',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
