# Generated by Django 3.0.6 on 2020-06-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_poll_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
