# Generated by Django 3.0.6 on 2020-08-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200624_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchChatter',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('latest_join', models.DateField()),
                ('latest_part', models.DateField(blank=True)),
            ],
        ),
    ]
