# Generated by Django 3.0.6 on 2020-08-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_twitchchatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchchatter',
            name='latest_join',
            field=models.DateField(blank=True),
        ),
    ]
