# Generated by Django 3.0.6 on 2020-08-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200801_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
